### PR TITLE
Create tr-tr.cfg

### LINKED ISSUE #44: Turkish (Türk) <tr-tr.cfg>
# Localization - ![Türk][TR] Turkish (Türk) <tr-tr.cfg>

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: type: localization
  * [x] Label: help-wanted
  * [x] Milestone: Localization - Master

### GameData

* [x] add  Localization\[tr-tr.cfg] 🗃️

### Translation

* [x] ![Türk][TR] Turkish (Türk) <tr-tr.cfg>

### Documentation

* [x] Update [readme.md] 🔢
* [x] Update [release.md] 🧾

### Wiki

* [x] Update docs/[localization.md]

## Update Social Media

* [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [ ] CurseForge
* [ ] Reddit
* [ ] Twitter @zer0Kerbal
* [ ] Forum
* [ ] Patreon
* [ ] SpaceDock
* [ ] CKAN (automated)

[lclztn]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/readme.md  "Localization"
[qs]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/quickstart.md "Quick Start"

[TR]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/master/img/TR.png "Turkish (Türk)"

### PR DESCRIPTION
**Pull request by zer0Kerbal**
### Localization

* Add
  * <tr-tr.cfg>
  * Teşekkürler, translated provided by @urrespect
  * ![Türk][TR] Turkish (Türk)
* closes #44 - Turkish (Türk) <tr-tr.cfg>
* updates #7 - Localization - Master

[TR]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/master/img/TR.png "Turkish (Türk)"

### CODE REVIEW

**Comment by urexpect** [comment]
yeah turkish and im native :) 
thanks

**Comment by zer0Kerbal** [comment]
> yeah turkish and im native :) thanks

Teşekkürler! I believe I am saying thank you!

**Comment by heckerelon** [comment]
♥️

**Comment by zer0Kerbal** [comment]
corrected spelling of @urexpect name

**Pull request merged**
